version: "3"
services:
  mongo:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
  graylog:
    image: graylog/graylog:2.3.0-1
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "514:514"
      - "5555:5555"
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api

